apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventrelay.name" . }}-config
  labels:
    {{- include "eventrelay.labels" . | nindent 4 }}
data:
  MYSQL_URL: {{ .Values.config.mysqlUrl | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  RABBITMQ_HOST: {{ .Values.config.rabbitmqHost | quote }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.config.otlpEndpoint | quote }}
  MANAGEMENT_ADDRESS: "0.0.0.0"
  MANAGEMENT_PORT: "8083"
  SERVER_PORT: "8080"
